[package]
name = "omnipaxos_storage"
version = "0.1.0"
authors = ["Abyel Tesfay <abyel@kth.se>", "Harald Ng <hng@kth.se>"]
edition = "2018"

[dependencies]
omnipaxos_core = { path = "../omnipaxos_core" }
commitlog = { version = "0.1", optional = false }
rocksdb = { version = "0.18.0", optional = false }
zerocopy = { version = "0.6.1", optional = false }

[dev-dependencies]
commitlog = "0.1"
rocksdb = "0.18.0"
zerocopy = "0.6.1"

[features]
# batch_accept = []
# latest_accepted = []
# continued_leader_reconfiguration = []
# default = ["latest_accepted", "continued_leader_reconfiguration", "batch_accept"]

#[profile.release]
#lto = true